### ISSUE TITLE
Makefile failed

### ISSUE THREAD

**Issue by ldmichel** [braunefe/BWEeval#1]
Hi,

I've downloaded the data and installed the requirements. However, upon execution (make -j 4 DEVICE=cpu), I got this error below. Would you have an idea how to solve this?

---
  File "./scripts/maxmarg/tripletModelConcat.py", line 64, in __call__
    pos = np.arccos(K.dot(source_norm,K.transpose(positive_norm)))
AttributeError: 'Tensor' object has no attribute 'arccos'
Makefile:284: recipe for target 'results/maxmarg/projections/general.cbow.2000.8.projection' failed
make: *** [results/maxmarg/projections/general.cbow.2000.8.projection] Error 1

**Comment by hangyav** [comment]
Thanks for reaching out.

Could you confirm that the correct versions of the required libs are installed? Please note that the project uses Theano instead of Tensorflow. It seems that your Keras installation runs tf. You might need to modify your Keras config to use Theano instead: https://keras.io/backend/

**Comment by ldmichel** [comment]
Thank you! Switching to Theano enabled the program to run.

**Comment by hangyav** [comment]
Great! I made this clear in the readme.

**Comment by anntanp** [comment]
> Great! I made this clear in the readme.

Hi Victor,

Thanks for the README.md! It might also be an idea to put a command in there as well like `export KERAS_BACKEND=theano`, because I also missed the same instruction just now... Also, for some reason, pip did not recognize "Cython", i changed it to lowercase ("cython") in the requirements.txt and it worked. Btw, I'm running on linux with a clean anaconda env (python=2.7).

**Comment by hangyav** [comment]
Hi,

Thanks for pointing these out. I updated the makefile with the KERAS_BACKEND variable so no need for manual keras config anymore. The problem with cython was caused by the fasttext dependency which I updated, so this should be ok as well.
